# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AKSync' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

pod 'Realm'
pod 'RealmSwift'

  use_frameworks!

  # Pods for AKSync

  

end
